#!/bin/sh

# XDG fallbacks (if not set, assume sensible defaults)
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

CONFIG="$XDG_DATA_HOME/dgbwm/.config/dgbwm/dgbwmrc"
[ -f "$CONFIG" ] && . "$CONFIG"

# Set wallpaper
if command -v feh >/dev/null 2>&1 && [ -n "$WALLPAPER" ]; then
    feh --bg-fill "$WALLPAPER" &
fi

dwmblocks &
dunst --config "$XDG_CONFIG_HOME/dunst/dunstrc" &

dgbwm_get_audio_sink --listen &
dgbwm_get_audio_source --listen &

if [ "${IS_LAPTOP:-0}" -eq 1 ]; then
    dgbwm_get_battery --listen &
fi

while true; do
        dwm 2>"$HOME/.dwm.log"
done
